version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2020!"
    ports:
      - "15432:5432"
    networks:
      - postgres_network
      
  web-pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "urtigah@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "15433:80"
    depends_on:
      - postgres
    networks:
      - postgres_network

networks: 
    postgres_network:
      driver: bridge