version: '3'

services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "37017:27017"
    networks:
      - mongo_network    

  mongo-express:
    image: mongo-express:latest
    ports:
      - 19081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: urtiga
      ME_CONFIG_BASICAUTH_PASSWORD: 123456
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
    depends_on:
      - mongo
    networks:
      - mongo_network

networks: 
    mongo_network:
      driver: bridge